### ISSUE TITLE
`Add node to cluster` task behavior

### ISSUE THREAD

**Issue by DimmKirr** [influxdata/ansible-influxdb-enterprise#6]
Could you please clarify how adding node to cluster is intended to work, specifically:

- How delegate_to login was designed to work
    - Which credentials are we supposed to be using to login to the 'slave' nodes? 
    - Currently it seems to me that I have to maintain ssh creds, so the leader can access 'slaves'.
    - What happens if the leader goes down, how do we handle that in Ansible (since we set the leader manually via `influx_meta_cluster_leader`)
- `ansible_hostname` is not very reliable, as it may (and will) contain non-fqdn address on AWS and other cloud systems - like `ip-10-10-10-10` which won't work across different domains/networks. Any objections to change it to `inventory_hostname` which will virtually guarantee network accessibility?

Mainly curious about the design intent here.

Thanks

**Comment by DimmKirr** [comment]
I think I figured it out. 

There is a strange bug that doesn't pass ssh authentication that is required for the `delegate_to`

The workaround looks like this:
```
- name: "{{ influx_node_type }} : Add node to cluster"
  command: "influxd-ctl add-{{ influx_node_type }} {{ ansible_hostname }}:{{ (influx_node_type == 'meta') | ternary(influx_meta_http_bind_port, influx_data_bind_port) }}"
  delegate_to: "{{ item }}"
  when:
    - influx_cluster_auto_join
    - influx_meta_cluster_leader is defined
  tags: ['influx', 'cluster', "{{ influx_node_type }}"]
  with_items: "{{ influx_meta_cluster_leader }}"
```

I will do more testing, but looks like that is it. 

(Ansible 2.2.0)
